---
kind: pipeline
name: webadmin-frontend

steps:
- name: build-prod
  image: node:10.15.3
  when:
    branch:
      - master
    event:
      - push
      - pull_request
  commands:
    - "[ -d node_module ] && rm -rf node_module"
    - npm install
    - npm run build

- name: deploy-prod
  image: drillster/drone-rsync
  when:
    branch:
      - master
    event:
      - push
      - pull_request
  environment:
    RSYNC_KEY:
      from_secret: deploy_key
    RSYNC_USER:
      from_secret: deploy_user
  settings:
    hosts: [code.artben.net]
    source: ./dist/*
    port:
      from_secret: deploy_port
    target: /data/tmp/webadmin
    include: []
    exclude: [.git,.vscode]
    script:
      - "[ -d /data/tmp/api/public ] && sudo chmod -R 777 /data/tmp/api/public"
